import type React from 'react'
import {
  BodyBeforeAfter,
  bodyBeforeAfterDefaultProps,
  BodyChecklist,
  bodyChecklistDefaultProps,
  BodyCompare,
  bodyCompareDefaultProps,
  BodyMythFact,
  bodyMythFactDefaultProps,
  BodyNumbered,
  bodyNumberedDefaultProps,
  BodyTipCard,
  bodyTipCardDefaultProps,
  BodyTimeline,
  bodyTimelineDefaultProps,
  BodyDiagram,
  bodyDiagramDefaultProps,
  BodyList,
  bodyListDefaultProps,
  BodyQuote,
  bodyQuoteDefaultProps,
  BodyStep,
  bodyStepDefaultProps,
  BodyText,
  bodyTextDefaultProps,
  CoverBold,
  coverBoldDefaultProps,
  CoverCentered,
  coverCenteredDefaultProps,
  CoverGradient,
  coverGradientDefaultProps,
  CoverMinimal,
  coverMinimalDefaultProps,
  CoverNumbered,
  coverNumberedDefaultProps,
  CoverBeforeAfter,
  CoverPhoto,
  coverPhotoDefaultProps,
  CoverPhotoTop,
  coverPhotoTopDefaultProps,
  BodyPhoto,
  bodyPhotoDefaultProps,
  coverBeforeAfterDefaultProps,
  CoverSplit,
  coverSplitDefaultProps,
  CTADM,
  ctaDMDefaultProps,
  CTAShare,
  ctaShareDefaultProps,
  CTAChecklistScore,
  ctaChecklistScoreDefaultProps,
  CTAFollow,
  ctaFollowDefaultProps,
  CTALink,
  ctaLinkDefaultProps,
  CTAQuestion,
  ctaQuestionDefaultProps,
  CTASave,
  ctaSaveDefaultProps,
  HookProblem,
  hookProblemDefaultProps,
  HookQuestion,
  hookQuestionDefaultProps,
  HookStat,
  hookStatDefaultProps,
  HookTeaser,
  hookTeaserDefaultProps,
  HookRoadmap,
  hookRoadmapDefaultProps,
  HookSelfQualify,
  hookSelfQualifyDefaultProps,
  HookVS,
  hookVSDefaultProps,
  HookMyth,
  hookMythDefaultProps,
  HookResult,
  hookResultDefaultProps,
  HookControversial,
  hookControversialDefaultProps,
  HookPainPoint,
  hookPainPointDefaultProps,
  HookListPreview,
  hookListPreviewDefaultProps,
  CoverRedacted,
  coverRedactedDefaultProps,
  CoverGlass,
  coverGlassDefaultProps,
  CoverMagazine,
  coverMagazineDefaultProps,
  HookChatBubble,
  hookChatBubbleDefaultProps,
  HookRedFlag,
  hookRedFlagDefaultProps,
  HookStory,
  hookStoryDefaultProps,
  BodyFAQ,
  bodyFAQDefaultProps,
  BodyDosDonts,
  bodyDosDontsDefaultProps,
  BodyScorecard,
  bodyScorecardDefaultProps,
  CTASummary,
  ctaSummaryDefaultProps,
  CTATestimonial,
  ctaTestimonialDefaultProps,
  CTASocialProof,
  ctaSocialProofDefaultProps,
  BodyGrowth,
  bodyGrowthDefaultProps,

  CoverEmoji, coverEmojiDefaultProps,
  CoverCountdown, coverCountdownDefaultProps,
  HookSwipeBait, hookSwipeBaitDefaultProps,
  HookHotTake, hookHotTakeDefaultProps,
  BodyStatGrid, bodyStatGridDefaultProps,
  BodyProcess, bodyProcessDefaultProps,
  CTACarouselEnd, ctaCarouselEndDefaultProps,
  CTAPoll, ctaPollDefaultProps,
} from '@/components/slide-templates'

export type PropSchemaType = 'string' | 'number' | 'boolean' | 'boolean[]' | 'color' | 'image' | 'string[]' | 'object[]|string[]' | 'enum'

export interface PropSchema {
  type: PropSchemaType
  label: string
  required?: boolean
  group?: 'content' | 'style'
  min?: number
  max?: number
  step?: number
  default?: any
  options?: { label: string; value: string }[]
  multiline?: boolean
  objectFields?: { key: string; label: string; type: 'string' | 'number' | 'enum'; options?: { label: string; value: string }[] }[]
  linkedTo?: string
}

export interface SlideTemplateInfo {
  id: string
  name: string
  category: 'cover' | 'hook' | 'body' | 'cta'
  description: string
  component: React.ComponentType<any>
  propsSchema: Record<string, PropSchema>
  defaultProps: Record<string, any>
}

const RAW_SLIDE_TEMPLATES: SlideTemplateInfo[] = [
  {
    id: 'cover-bold',
    name: 'CoverBold',
    category: 'cover',
    description: '큰 임팩트 텍스트, 배경 이미지/색상',
    component: CoverBold,
    propsSchema: {
      title: { type: 'string', label: '제목', required: true },
      subtitle: { type: 'string', label: '부제목' },
      tag: { type: 'string', label: '태그' },
      backgroundImageUrl: { type: 'image', label: '배경 이미지' },
      // Style overrides
      titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 60, max: 120, step: 2, default: 94 },
      subtitleFontSize: { type: 'number', label: '부제목 크기', group: 'style', min: 30, max: 80, step: 2, default: 56 },
      tagFontSize: { type: 'number', label: '태그 크기', group: 'style', min: 20, max: 60, step: 2, default: 38 },
      showAccentBar: { type: 'boolean', label: '악센트 바 표시', group: 'style', default: true },
      barWidth: { type: 'number', label: '바 너비', group: 'style', min: 60, max: 300, step: 4, default: 176 },
      paddingX: { type: 'number', label: '좌우 패딩', group: 'style', min: 32, max: 120, step: 4, default: 64 },
      backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' },
      accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' },
      accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' },
      textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' },
    },
    defaultProps: coverBoldDefaultProps,
  },
  { id: 'cover-centered', name: 'CoverCentered', category: 'cover', description: '중앙 정렬, 깔끔한 타이틀', component: CoverCentered, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, kicker: { type: 'string', label: '상단 카피' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 98 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverCenteredDefaultProps },
  { id: 'cover-minimal', name: 'CoverMinimal', category: 'cover', description: '미니멀, 여백 중심', component: CoverMinimal, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, issue: { type: 'string', label: '이슈 라벨' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 86 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 48 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverMinimalDefaultProps },
  { id: 'cover-split', name: 'CoverSplit', category: 'cover', description: '좌우 분할 (이미지 + 텍스트)', component: CoverSplit, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, imageUrl: { type: 'image', label: '좌측 이미지' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 78 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 48 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverSplitDefaultProps },
  { id: 'cover-gradient', name: 'CoverGradient', category: 'cover', description: '그라디언트 배경 + 타이틀', component: CoverGradient, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, gradientFrom: { type: 'color', label: '그라디언트 시작' }, gradientTo: { type: 'color', label: '그라디언트 끝' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 100 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 48 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverGradientDefaultProps },
  { id: 'cover-numbered', name: 'CoverNumbered', category: 'cover', description: '넘버 시리즈 커버', component: CoverNumbered, propsSchema: { number: { type: 'string', label: '숫자' }, title: { type: 'string', label: '제목' }, subtitle: { type: 'string', label: '부제목' }, tag: { type: 'string', label: '태그' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 80 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 48 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverNumberedDefaultProps },
  { id: 'cover-before-after', name: 'CoverBeforeAfter', category: 'cover', description: 'Before/After 분할 커버', component: CoverBeforeAfter, propsSchema: { beforeText: { type: 'string', label: 'Before 텍스트' }, afterText: { type: 'string', label: 'After 텍스트' }, tag: { type: 'string', label: '태그' }, subtitle: { type: 'string', label: '하단 안내' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 80 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 48 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverBeforeAfterDefaultProps },
  { id: "cover-photo", name: "CoverPhoto", category: "cover", description: "전면 사진 + 텍스트 오버레이", component: CoverPhoto, propsSchema: { title: { type: "string", label: "제목", required: true }, subtitle: { type: "string", label: "부제목" }, imageUrl: { type: "image", label: "배경 이미지" }, overlayOpacity: { type: "number", label: "오버레이 투명도", min: 0, max: 1, step: 0.05, group: "style", default: 0.55 }, tag: { type: "string", label: "태그" } , textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverPhotoDefaultProps },
  { id: "cover-photo-top", name: "CoverPhotoTop", category: "cover", description: "상단 사진 + 하단 텍스트", component: CoverPhotoTop, propsSchema: { title: { type: "string", label: "제목", required: true }, subtitle: { type: "string", label: "부제목" }, imageUrl: { type: "image", label: "상단 이미지" }, tag: { type: "string", label: "태그" } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 40, max: 120, step: 2, default: 62 }, subtitleFontSize: { type: "number", label: "부제목 크기", group: "style", min: 24, max: 80, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: coverPhotoTopDefaultProps },
  { id: 'cover-redacted', name: 'CoverRedacted', category: 'cover', description: '텍스트 가림 호기심 유발', component: CoverRedacted, propsSchema: { title: { type: 'string', label: '제목 (█로 가림)', required: true }, redactedWord: { type: 'string', label: '숨겨진 단어' }, subtitle: { type: 'string', label: '부제목' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 40, max: 120, step: 2, default: 94 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: coverRedactedDefaultProps },
  { id: 'cover-glass', name: 'CoverGlass', category: 'cover', description: 'Glassmorphism 카드', component: CoverGlass, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, backgroundImageUrl: { type: 'image', label: '배경 이미지' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 40, max: 120, step: 2, default: 86 }, subtitleFontSize: { type: 'number', label: '부제목 크기', group: 'style', min: 24, max: 80, step: 2, default: 56 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: coverGlassDefaultProps },
  { id: 'cover-magazine', name: 'CoverMagazine', category: 'cover', description: '잡지 표지 레이아웃', component: CoverMagazine, propsSchema: { masthead: { type: 'string', label: '매거진명' }, headline: { type: 'string', label: '헤드라인', required: true }, subHeadline: { type: 'string', label: '서브 헤드라인' }, issueLabel: { type: 'string', label: '이슈 라벨' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 60, max: 160, step: 2, default: 110 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: coverMagazineDefaultProps },

  { id: 'hook-question', name: 'HookQuestion', category: 'hook', description: '질문형 훅', component: HookQuestion, propsSchema: { question: { type: 'string', label: '질문', required: true }, subQuestion: { type: 'string', label: '보조 질문' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 96 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookQuestionDefaultProps },
  {
    id: 'hook-stat', name: 'HookStat', category: 'hook', description: '통계 숫자 강조', component: HookStat,
    propsSchema: {
      statValue: { type: 'string', label: '숫자', required: true },
      statLabel: { type: 'string', label: '라벨' },
      detail: { type: 'string', label: '설명' },
      // Style overrides
      statFontSize: { type: 'number', label: '숫자 크기', group: 'style', min: 80, max: 300, step: 2, default: 220 },
      labelFontSize: { type: 'number', label: '라벨 크기', group: 'style', min: 30, max: 120, step: 2, default: 64 },
      detailFontSize: { type: 'number', label: '설명 크기', group: 'style', min: 24, max: 80, step: 2, default: 44 },
      overlineText: { type: 'string', label: '오버라인 텍스트', group: 'style', default: 'impact metric' },
      showOverline: { type: 'boolean', label: '오버라인 표시', group: 'style', default: true },
      showAccentBar: { type: 'boolean', label: '악센트 바 표시', group: 'style', default: true },
      barWidth: { type: 'number', label: '바 너비', group: 'style', min: 60, max: 300, step: 4, default: 160 },
      paddingX: { type: 'number', label: '좌우 패딩', group: 'style', min: 32, max: 120, step: 4, default: 64 },
    },
    defaultProps: hookStatDefaultProps,
  },
  { id: 'hook-problem', name: 'HookProblem', category: 'hook', description: '문제 제기형', component: HookProblem, propsSchema: { title: { type: 'string', label: '제목' }, points: { type: 'string[]', label: '문제 목록' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 82 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookProblemDefaultProps },
  { id: 'hook-teaser', name: 'HookTeaser', category: 'hook', description: '티저/예고형', component: HookTeaser, propsSchema: { overline: { type: 'string', label: '오버라인' }, title: { type: 'string', label: '제목', required: true }, teaser: { type: 'string', label: '티저 문구' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 90 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookTeaserDefaultProps },
  { id: 'hook-roadmap', name: 'HookRoadmap', category: 'hook', description: '목차/로드맵', component: HookRoadmap, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'string[]', label: '항목' }, subtitle: { type: 'string', label: '하단 안내' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 66 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookRoadmapDefaultProps },
  { id: 'hook-self-qualify', name: 'HookSelfQualify', category: 'hook', description: '타겟 셀프체크', component: HookSelfQualify, propsSchema: { title: { type: 'string', label: '제목' }, conditions: { type: 'string[]', label: '조건 목록' }, conclusion: { type: 'string', label: '결론' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 82 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookSelfQualifyDefaultProps },
  { id: 'hook-vs', name: 'HookVS', category: 'hook', description: 'A vs B 대결', component: HookVS, propsSchema: { leftLabel: { type: 'string', label: '왼쪽' }, rightLabel: { type: 'string', label: '오른쪽' }, title: { type: 'string', label: '제목' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 96 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookVSDefaultProps },
  { id: 'hook-myth', name: 'HookMyth', category: 'hook', description: '착각 깨기', component: HookMyth, propsSchema: { myth: { type: 'string', label: '착각' }, reveal: { type: 'string', label: '진실' }, label: { type: 'string', label: '라벨' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 82 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookMythDefaultProps },
  { id: 'hook-result', name: 'HookResult', category: 'hook', description: '결과 임팩트', component: HookResult, propsSchema: { result: { type: 'string', label: '결과' }, context: { type: 'string', label: '맥락' }, overline: { type: 'string', label: '오버라인' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 120 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookResultDefaultProps },
  { id: 'hook-controversial', name: 'HookControversial', category: 'hook', description: '논란/도발', component: HookControversial, propsSchema: { statement: { type: 'string', label: '주장' }, subtext: { type: 'string', label: '보조 텍스트' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 94 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookControversialDefaultProps },
  { id: 'hook-pain-point', name: 'HookPainPoint', category: 'hook', description: '공감 페인포인트', component: HookPainPoint, propsSchema: { painPoint: { type: 'string', label: '페인포인트' }, empathy: { type: 'string', label: '공감' }, transition: { type: 'string', label: '전환 문구' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 82 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookPainPointDefaultProps },
  { id: 'hook-list-preview', name: 'HookListPreview', category: 'hook', description: '리스트 미리보기', component: HookListPreview, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'string[]', label: '항목' }, revealCount: { type: 'number', label: '공개 수', min: 1, max: 10, step: 1 }, overline: { type: 'string', label: '오버라인' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 36, max: 120, step: 2, default: 66 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: hookListPreviewDefaultProps },
  { id: 'hook-chat-bubble', name: 'HookChatBubble', category: 'hook', description: '메신저 대화형', component: HookChatBubble, propsSchema: { title: { type: 'string', label: '제목' }, messages: { type: 'string[]', label: '메시지 (홀수=오른쪽, 짝수=왼쪽)' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 120, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '메시지 크기', group: 'style', min: 20, max: 60, step: 2, default: 36 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: hookChatBubbleDefaultProps },
  { id: 'hook-red-flag', name: 'HookRedFlag', category: 'hook', description: 'Red Flag vs Green Flag', component: HookRedFlag, propsSchema: { title: { type: 'string', label: '제목' }, redFlags: { type: 'string[]', label: 'Red Flag 목록' }, greenFlags: { type: 'string[]', label: 'Green Flag 목록' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 120, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '항목 크기', group: 'style', min: 20, max: 60, step: 2, default: 34 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: hookRedFlagDefaultProps },
  { id: 'hook-story', name: 'HookStory', category: 'hook', description: '개인 스토리 오프닝', component: HookStory, propsSchema: { opening: { type: 'string', label: '오프닝' }, body: { type: 'string', label: '본문' }, transition: { type: 'string', label: '전환 문구' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 120, step: 2, default: 82 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: hookStoryDefaultProps },

  {
    id: 'body-text', name: 'BodyText', category: 'body', description: '설명형 본문', component: BodyText,
    propsSchema: {
      heading: { type: 'string', label: '제목' },
      body: { type: 'string', label: '본문' },
      // Style overrides
      headingFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 100, step: 2, default: 62 },
      bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 24, max: 60, step: 2, default: 38 },
      showAccentBar: { type: 'boolean', label: '악센트 바 표시', group: 'style', default: true },
      headingBodyGap: { type: 'number', label: '제목-본문 간격', group: 'style', min: 20, max: 120, step: 4, default: 64 },
      paddingX: { type: 'number', label: '좌우 패딩', group: 'style', min: 32, max: 120, step: 4, default: 64 },
    },
    defaultProps: bodyTextDefaultProps,
  },
  { id: 'body-list', name: 'BodyList', category: 'body', description: '리스트/불릿', component: BodyList, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'string[]', label: '리스트' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyListDefaultProps },
  { id: 'body-step', name: 'BodyStep', category: 'body', description: '넘버링 단계별', component: BodyStep, propsSchema: { title: { type: 'string', label: '제목' }, steps: { type: 'object[]|string[]', label: '단계 목록' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyStepDefaultProps },
  { id: 'body-compare', name: 'BodyCompare', category: 'body', description: 'Before/After 비교', component: BodyCompare, propsSchema: { title: { type: 'string', label: '제목' }, beforeTitle: { type: 'string', label: 'Before 제목' }, beforeDesc: { type: 'string', label: 'Before 설명' }, beforeItems: { type: 'string[]', label: 'Before 항목' }, afterTitle: { type: 'string', label: 'After 제목' }, afterDesc: { type: 'string', label: 'After 설명' }, afterItems: { type: 'string[]', label: 'After 항목' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyCompareDefaultProps },
  { id: 'body-diagram', name: 'BodyDiagram', category: 'body', description: '플로우/다이어그램', component: BodyDiagram, propsSchema: { title: { type: 'string', label: '제목' }, nodes: { type: 'string[]', label: '노드 목록' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyDiagramDefaultProps },
  { id: 'body-quote', name: 'BodyQuote', category: 'body', description: '인용구/명언', component: BodyQuote, propsSchema: { quote: { type: 'string', label: '인용문', multiline: true }, author: { type: 'string', label: '저자' } , titleFontSize: { type: "number", label: "인용문 크기", group: "style", min: 20, max: 100, step: 2, default: 42 }, titleLineHeight: { type: "number", label: "인용문 행간", group: "style", min: 1.0, max: 2.5, step: 0.1, default: 1.6 }, bodyFontSize: { type: "number", label: "저자 크기", group: "style", min: 16, max: 60, step: 2, default: 28 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyQuoteDefaultProps },
  { id: 'body-checklist', name: 'BodyChecklist', category: 'body', description: '체크리스트', component: BodyChecklist, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'string[]', label: '항목' }, checked: { type: 'boolean[]', label: '체크 여부', linkedTo: 'items' }, titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyChecklistDefaultProps },
  { id: 'body-myth-fact', name: 'BodyMythFact', category: 'body', description: 'Myth vs Fact', component: BodyMythFact, propsSchema: { myth: { type: 'string', label: 'Myth' }, fact: { type: 'string', label: 'Fact' }, mythLabel: { type: 'string', label: 'Myth 라벨' }, factLabel: { type: 'string', label: 'Fact 라벨' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 56 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyMythFactDefaultProps },
  { id: 'body-before-after', name: 'BodyBeforeAfter', category: 'body', description: 'Before → After', component: BodyBeforeAfter, propsSchema: { beforeTitle: { type: 'string', label: 'Before 제목' }, beforeBody: { type: 'string', label: 'Before 내용' }, afterTitle: { type: 'string', label: 'After 제목' }, afterBody: { type: 'string', label: 'After 내용' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyBeforeAfterDefaultProps },
  { id: "body-photo", name: "BodyPhoto", category: "body", description: "사진 + 텍스트 (위치 선택)", component: BodyPhoto, propsSchema: { title: { type: "string", label: "제목", required: true }, body: { type: "string", label: "본문" }, imageUrl: { type: "image", label: "이미지" }, imagePosition: { type: "string", label: "이미지 위치 (top/bottom/left/right)" } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyPhotoDefaultProps },
  { id: 'body-numbered', name: 'BodyNumbered', category: 'body', description: '넘버 포인트', component: BodyNumbered, propsSchema: { number: { type: 'string', label: '번호' }, title: { type: 'string', label: '제목' }, body: { type: 'string', label: '본문' }, totalLabel: { type: 'string', label: '전체 표시' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyNumberedDefaultProps },
  { id: 'body-tip-card', name: 'BodyTipCard', category: 'body', description: '팁 카드', component: BodyTipCard, propsSchema: { emoji: { type: 'string', label: '이모지' }, title: { type: 'string', label: '제목' }, body: { type: 'string', label: '본문' }, tipNumber: { type: 'string', label: '팁 번호' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyTipCardDefaultProps },
  { id: 'body-timeline', name: 'BodyTimeline', category: 'body', description: '타임라인', component: BodyTimeline, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'object[]|string[]', label: '타임라인 항목' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, bodyFontSize: { type: "number", label: "본문 크기", group: "style", min: 20, max: 60, step: 2, default: 36 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: bodyTimelineDefaultProps },
  { id: 'body-faq', name: 'BodyFAQ', category: 'body', description: 'Q&A 카드', component: BodyFAQ, propsSchema: { question: { type: 'string', label: '질문', required: true }, answer: { type: 'string', label: '답변' }, tag: { type: 'string', label: '태그' }, titleFontSize: { type: 'number', label: '질문 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '답변 크기', group: 'style', min: 20, max: 60, step: 2, default: 36 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: bodyFAQDefaultProps },
  { id: 'body-dos-donts', name: 'BodyDosDonts', category: 'body', description: 'Do vs Don\'t', component: BodyDosDonts, propsSchema: { title: { type: 'string', label: '제목' }, dos: { type: 'string[]', label: 'Do 목록' }, donts: { type: 'string[]', label: 'Don\'t 목록' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 20, max: 60, step: 2, default: 36 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: bodyDosDontsDefaultProps },
  { id: 'body-growth', name: 'BodyGrowth', category: 'body', description: 'Before→After 성장 비교', component: BodyGrowth, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'object[]|string[]', label: '항목', objectFields: [{ key: 'label', label: '항목명', type: 'string' }, { key: 'before', label: 'Before', type: 'number' }, { key: 'after', label: 'After', type: 'number' }, { key: 'unit', label: '단위', type: 'enum', options: [{ label: '없음', value: 'none' }, { label: '%', value: 'percent' }, { label: '₩', value: 'won' }] }] }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '항목 크기', group: 'style', min: 20, max: 60, step: 2, default: 34 }, cardWidth: { type: 'number', label: '카드 너비', group: 'style', min: 400, max: 940, step: 10, default: 700 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: bodyGrowthDefaultProps },
  { id: 'body-scorecard', name: 'BodyScorecard', category: 'body', description: '점수 바 차트', component: BodyScorecard, propsSchema: { title: { type: 'string', label: '제목' }, items: { type: 'object[]|string[]', label: '항목', objectFields: [{ key: 'label', label: '항목명', type: 'string' }, { key: 'score', label: '점수', type: 'number' }, { key: 'max', label: '만점', type: 'number' }] }, maxScore: { type: 'number', label: '만점 (기본)', min: 10, max: 100000, step: 10 }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '항목 크기', group: 'style', min: 20, max: 60, step: 2, default: 34 }, barHeight: { type: 'number', label: '게이지 높이', group: 'style', min: 4, max: 32, step: 2, default: 12 }, cardWidth: { type: 'number', label: '카드 너비', group: 'style', min: 400, max: 940, step: 10, default: 700 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: bodyScorecardDefaultProps },

  { id: 'cta-follow', name: 'CTAFollow', category: 'cta', description: '팔로우 유도', component: CTAFollow, propsSchema: { title: { type: 'string', label: '제목' }, handle: { type: 'string', label: '핸들' }, reason: { type: 'string', label: '설명' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 68 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaFollowDefaultProps },
  { id: 'cta-save', name: 'CTASave', category: 'cta', description: '저장 유도', component: CTASave, propsSchema: { title: { type: 'string', label: '제목' }, subtitle: { type: 'string', label: '설명' }, tip: { type: 'string', label: '팁' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 84 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaSaveDefaultProps },
  { id: 'cta-link', name: 'CTALink', category: 'cta', description: '링크/프로필 유도', component: CTALink, propsSchema: { title: { type: 'string', label: '제목' }, linkLabel: { type: 'string', label: '링크 라벨' }, linkValue: { type: 'string', label: '링크 주소' }, caption: { type: 'string', label: '설명' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 72 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaLinkDefaultProps },
  {
    id: 'cta-question', name: 'CTAQuestion', category: 'cta', description: '댓글 유도 질문', component: CTAQuestion,
    propsSchema: {
      question: { type: 'string', label: '질문' },
      guide: { type: 'string', label: '안내' },
      prompt: { type: 'string', label: '해시태그/프롬프트' },
      // Style overrides
      questionFontSize: { type: 'number', label: '질문 크기', group: 'style', min: 40, max: 120, step: 2, default: 74 },
      guideFontSize: { type: 'number', label: '안내 크기', group: 'style', min: 18, max: 50, step: 2, default: 30 },
      promptFontSize: { type: 'number', label: '프롬프트 크기', group: 'style', min: 20, max: 60, step: 2, default: 36 },
      padding: { type: 'number', label: '패딩', group: 'style', min: 32, max: 140, step: 4, default: 80 },
    },
    defaultProps: ctaQuestionDefaultProps,
  },
  { id: 'cta-dm', name: 'CTADM', category: 'cta', description: 'DM 유도', component: CTADM, propsSchema: { title: { type: 'string', label: '제목' }, keyword: { type: 'string', label: '키워드' }, description: { type: 'string', label: '설명' }, prompt: { type: 'string', label: '해시태그' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaDMDefaultProps },
  { id: 'cta-share', name: 'CTAShare', category: 'cta', description: '공유 유도', component: CTAShare, propsSchema: { title: { type: 'string', label: '제목' }, targetPerson: { type: 'string', label: '대상' }, reason: { type: 'string', label: '이유' }, prompt: { type: 'string', label: '해시태그' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaShareDefaultProps },
  { id: 'cta-checklist-score', name: 'CTAChecklistScore', category: 'cta', description: '점수 카드', component: CTAChecklistScore, propsSchema: { title: { type: 'string', label: '제목' }, footer: { type: 'string', label: '하단 안내' }, prompt: { type: 'string', label: '해시태그' } , titleFontSize: { type: "number", label: "제목 크기", group: "style", min: 30, max: 100, step: 2, default: 66 }, textAlign: { type: "string", label: "텍스트 정렬 (left/center/right)", group: "style" }, backgroundColor: { type: "color", label: "배경색", group: "style", default: '#0a0a0a' }, accentColor: { type: "color", label: "강조색", group: "style", default: '#ff6b6b' }, textColor: { type: "color", label: "텍스트 색", group: "style", default: '#ffffff' }}, defaultProps: ctaChecklistScoreDefaultProps },
  { id: 'cta-summary', name: 'CTASummary', category: 'cta', description: '요약 정리 + CTA', component: CTASummary, propsSchema: { title: { type: 'string', label: '제목' }, points: { type: 'string[]', label: '요약 포인트' }, cta: { type: 'string', label: 'CTA 문구' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 20, max: 60, step: 2, default: 34 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: ctaSummaryDefaultProps },
  { id: 'cta-testimonial', name: 'CTATestimonial', category: 'cta', description: '고객 후기 + CTA', component: CTATestimonial, propsSchema: { quote: { type: 'string', label: '후기 인용문' }, author: { type: 'string', label: '작성자' }, role: { type: 'string', label: '직함' }, cta: { type: 'string', label: 'CTA 문구' }, titleFontSize: { type: 'number', label: '인용문 크기', group: 'style', min: 30, max: 80, step: 2, default: 44 }, bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 20, max: 60, step: 2, default: 34 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: ctaTestimonialDefaultProps },
  { id: 'cta-social-proof', name: 'CTASocialProof', category: 'cta', description: '소셜 프루프 + CTA', component: CTASocialProof, propsSchema: { title: { type: 'string', label: '제목' }, metrics: { type: 'object[]|string[]', label: '지표 ({value, label})' }, cta: { type: 'string', label: 'CTA 버튼' }, handle: { type: 'string', label: '핸들' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 68 }, bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 20, max: 80, step: 2, default: 48 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' }}, defaultProps: ctaSocialProofDefaultProps },
  { id: 'cover-emoji', name: 'CoverEmoji', category: 'cover', description: '이모지 + 제목 (스크롤 스톱)', component: CoverEmoji, propsSchema: { emoji: { type: 'string', label: '이모지' }, title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 40, max: 120, step: 2, default: 94 }, subtitleFontSize: { type: 'number', label: '부제목 크기', group: 'style', min: 24, max: 80, step: 2, default: 56 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: coverEmojiDefaultProps },
  { id: 'cover-countdown', name: 'CoverCountdown', category: 'cover', description: '카운트다운 숫자 커버', component: CoverCountdown, propsSchema: { count: { type: 'string', label: '숫자' }, title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 40, max: 120, step: 2, default: 80 }, subtitleFontSize: { type: 'number', label: '부제목 크기', group: 'style', min: 24, max: 80, step: 2, default: 36 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: coverCountdownDefaultProps },
  { id: 'hook-swipe-bait', name: 'HookSwipeBait', category: 'hook', description: '스와이프 유도 (블러 힌트)', component: HookSwipeBait, propsSchema: { title: { type: 'string', label: '제목', required: true }, blurredHint: { type: 'string', label: '블러 힌트' }, swipeText: { type: 'string', label: '스와이프 안내' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 120, step: 2, default: 82 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: hookSwipeBaitDefaultProps },
  { id: 'hook-hot-take', name: 'HookHotTake', category: 'hook', description: '핫테이크 (논쟁 유발)', component: HookHotTake, propsSchema: { label: { type: 'string', label: '라벨' }, opinion: { type: 'string', label: '의견', required: true }, context: { type: 'string', label: '맥락' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 36, max: 120, step: 2, default: 90 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: hookHotTakeDefaultProps },
  { id: 'body-stat-grid', name: 'BodyStatGrid', category: 'body', description: '숫자 통계 그리드 (2x2/3x2)', component: BodyStatGrid, propsSchema: { title: { type: 'string', label: '제목', required: true }, stats: { type: 'object[]|string[]', label: '통계 ({value, label})' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '숫자 크기', group: 'style', min: 30, max: 100, step: 2, default: 64 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: bodyStatGridDefaultProps },
  { id: 'body-process', name: 'BodyProcess', category: 'body', description: '프로세스 플로우 (연결선)', component: BodyProcess, propsSchema: { title: { type: 'string', label: '제목', required: true }, steps: { type: 'string[]', label: '단계 목록' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, bodyFontSize: { type: 'number', label: '본문 크기', group: 'style', min: 20, max: 60, step: 2, default: 38 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: bodyProcessDefaultProps },
  { id: 'cta-carousel-end', name: 'CTACarouselEnd', category: 'cta', description: '끝까지 본 당신 + 행동 유도', component: CTACarouselEnd, propsSchema: { title: { type: 'string', label: '제목', required: true }, subtitle: { type: 'string', label: '부제목' }, actions: { type: 'object[]|string[]', label: '행동 목록', objectFields: [{ key: 'label', label: '라벨', type: 'string' }, { key: 'value', label: '링크/연락처', type: 'string' }] }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: ctaCarouselEndDefaultProps },
  { id: 'cta-poll', name: 'CTAPoll', category: 'cta', description: '투표/선택형 CTA', component: CTAPoll, propsSchema: { question: { type: 'string', label: '질문', required: true }, options: { type: 'string[]', label: '선택지' }, prompt: { type: 'string', label: 'CTA 문구' }, titleFontSize: { type: 'number', label: '제목 크기', group: 'style', min: 30, max: 100, step: 2, default: 62 }, backgroundColor: { type: 'color', label: '배경색', group: 'style', default: '#0a0a0a' }, accentColor: { type: 'color', label: '강조색', group: 'style', default: '#ff6b6b' }, accentColorEnd: { type: 'color', label: '강조 끝색 (그라디언트)', group: 'style' }, textColor: { type: 'color', label: '텍스트 색', group: 'style', default: '#ffffff' } }, defaultProps: ctaPollDefaultProps },
]

export const SLIDE_TEMPLATES: SlideTemplateInfo[] = RAW_SLIDE_TEMPLATES.map((template) => ({
  ...template,
  propsSchema: {
    ...template.propsSchema,
    slideNumber: { type: 'string', label: '슬라이드 번호' },
    textAlign: {
      type: 'enum' as PropSchemaType,
      label: '텍스트 정렬',
      group: 'style' as const,
      default: 'center',
      options: [
        { label: '왼쪽', value: 'left' },
        { label: '가운데', value: 'center' },
        { label: '오른쪽', value: 'right' },
      ],
    },
  },
}))

export function getSlideTemplate(id: string) {
  return SLIDE_TEMPLATES.find((template) => template.id === id)
}